<?php
namespace app\system\controller;
use think\Controller;
use think\View;
use think\Db;
class Install extends Controller{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $filename = 'install.lock';
        if (file_exists($filename)) {
            die("系统已安装，请不要重复安装");
        }
    }
    public function index(){
        return View("system@/index");
    }
    public function check_db_info(){
        try{
            $sql = mysqli_connect(input('db_ip'),input('db_username'),input('db_password'),'',input('db_port'));
        }catch(\Exception $e){
            return ["status"=>0,"reason"=>"数据库信息不正确，无法连接到数据库"];
        }
        return ["status"=>1];
    }
    public function create_db(){
        $sql = mysqli_connect(input('db_ip'),input('db_username'),input('db_password'),'',input('db_port'));
        $db = mysqli_select_db($sql,input('db_name'));
        if(!$db){
            if(!mysqli_query($sql,"CREATE DATABASE ".input('db_name'))){
                return ["status"=>0,"reason"=>"无法新建数据库"];
            }
        }
        return ["status"=>1];
    }
    public function save_db_info(){
        set_db_config(["username","password","hostname","database","hostport","prefix"],
            [input('db_username'),input('db_password'),input('db_ip'),input('db_name'),input('db_port'),'']);
        return ["status"=>1];
    }
    public function create_table(){
        $sql = mysqli_connect(input('db_ip'),input('db_username'),input('db_password'),'',input('db_port'));
        $db = mysqli_select_db($sql,input('db_name'));
        $sqls = [
            "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";",
            "SET time_zone = \"+00:00\";",
            "CREATE TABLE IF NOT EXISTS `user` (`id` int(10) NOT NULL,`username` varchar(100) CHARACTER SET utf8mb4 NOT NULL,`password` varchar(100) CHARACTER SET utf8mb4 NOT NULL,`role` int(10) NOT NULL,`last_login_time` int(10) DEFAULT NULL,`last_login_ip` varchar(20) CHARACTER SET utf8mb4 DEFAULT NULL,`auth_token` varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL,`auth_token_time` int(10) DEFAULT NULL) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;",
            "ALTER TABLE `user` ADD PRIMARY KEY (`id`);",
            "ALTER TABLE `user` MODIFY `id` int(10) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=2;",
            "CREATE TABLE IF NOT EXISTS `role` (`id` int(10) NOT NULL,`role_name` varchar(100) CHARACTER SET utf8mb4 NOT NULL,`description` varchar(1000) CHARACTER SET utf8 NOT NULL,`value` varchar(1000) CHARACTER SET utf8mb4 NOT NULL) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;",
            "ALTER TABLE `role` ADD PRIMARY KEY (`id`);",
            "ALTER TABLE `role` MODIFY `id` int(10) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=4;",
            "CREATE TABLE IF NOT EXISTS `system_log` (`id` int(10) NOT NULL,`type` varchar(100) CHARACTER SET utf8mb4 NOT NULL,`content` varchar(1000) CHARACTER SET utf8mb4 NOT NULL,`username` varchar(100) CHARACTER SET utf8mb4 NOT NULL,`ip` varchar(100) CHARACTER SET utf8mb4 NOT NULL,`time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8;",
            "ALTER TABLE `system_log` ADD PRIMARY KEY (`id`);",
            "ALTER TABLE `system_log` MODIFY `id` int(10) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=4;",
        ];
        foreach ($sqls as $vo){
            mysqli_query($sql,$vo);
        }
        db("role")->insert(['id'=>1,'role_name'=>'超级管理员','description'=>'什么都可以做','value'=>'0']);
        return ["status"=>1];
    }
    public function save_admin_info(){
        db("user")->insert(['username'=>input('admin_username'),'password'=>md5(input('admin_password')),'role'=>1,'last_login_time'=>0,'last_login_ip'=>'','auth_token'=>'','auth_token_time'=>0]);
        $myfile = fopen("install.lock", "w");
        fclose($myfile);
        return ["status"=>1];
    }
}